EOS testing: changed trap sig and added a trap cleanup function

diff --git a/asg_1/stats b/asg_1/stats
--- a/asg_1/stats
+++ b/asg_1/stats
@@ -1,4 +1,5 @@
 #!/bin/bash
+trap trap_cleanup SIGTERM SIGHUP SIGINT
 
 # variables and functions
 ROW_AVG=0
@@ -62,20 +63,25 @@ function setup {
 }
 # uses to delete all tmpfiles on program finish or trap call
 function cleanup {
-                rm -f *$$
+                rm -f tmp$$ tmp1$$ converted$$ average$$ median$$
 }
+# clean up function for trap
+function trap_cleanup {
+                rm -f tmp$$ tmp1$$ converted$$ average$$ median$$
+                exit 1
+        }
 #####################################################################
 ##                    Start of the Program                         ##
 #####################################################################
 
 setup
-trap cleanup SIGHUP SIGINT SIGTERM
+
 
 # Check the argument length
 if [ "$#" -gt "2" ]
 then
         cleanup
-        echo "Too many arguments" >&2
+        echo "Usage: stats {-r|-c} [file]" >&2
         exit 1
 fi
 
@@ -90,7 +96,7 @@ fi
 if [ "$#" == "0" ] # no arguments then exit
 then
         cleanup
-        echo "Not enough arguments" >&2
+        echo "Usage: stats {-r|-c} [file]" >&2
         exit 1
 fi
 
@@ -98,14 +104,14 @@ fi
 if [ ! -s $FILE ]
 then
         cleanup
-        echo "File{$2} is empty or doesnt exist" >&2
+        echo "$2 is empty or doesnt exist" >&2
         exit 1
 fi
 # check if file is readable
 if [ ! -r $FILE ]
 then
         cleanup
-        echo "File {$2} is not readable" >&2
+        echo "$2 is not readable" >&2
         exit 1
 fi
 # Check for rows flag or default 1 argument
@@ -124,8 +130,6 @@ then
         exit 0
 else
         cleanup
-        echo "Bad option or bad format" >&2
+        echo "Usage: stats {-r|-c} [file]" >&2
         exit 1
 fi
-
-
